### ISSUE TITLE
login.cgi

### ISSUE THREAD

**Issue by philconner** [ChipwizBen/TheMachine#1]
After editing the appropriate block of code in common.pl to setup LDAP authentication when logging in, login fails. In the httpd error log I see this line for every login attempt:

>  login.cgi: DBD::mysql::st execute failed: Column 'username' cannot be null at /opt/TheMachine/HTTP/login.cgi line 72

Looking through the manual, it seems the login.cgi file is not meant to be edited; is this an issue?

**Comment by ChipwizBen** [comment]
Is it LDAP or Active Directory you're trying with?

Does the user you're trying to login with have the "displayName" attribute set? If not, can you trying changing "displayName" to "userPrincipalName" on this line in your common.pl file:
https://github.com/ChipwizBen/TheMachine/blob/master/HTTP/common.pl#L191

From this:
```
$Display_Name = $User_Values->get_value("displayName");
$Email = $User_Values->get_value("mail");
```
To this:
```
$Display_Name = $User_Values->get_value("userPrincipalName");
$Email = $User_Values->get_value("mail");
```

And let me know if that solves it? If that fixes it for you, I'll release a proper fix for it in the next couple of days with version 2.6 (which is nearly finished).

**Comment by philconner** [comment]
I was trying to setup LDAP authentication against an Active Directory domain controller. Unfortunately the fix you suggested didn't work, but I found a workaround that works for my purposes.

To debug, I printed out the value of $LDAP_Login right after line 49 in login.cgi, and it returned "Success,,", so somehow the $Display_Name and $Email variables from common.pl lines 191-192 were empty.

As a workaround, I changed line 48 in login.cgi to:

`my $LDAP_User_Name = $User_Name_Form;`

and this allowed me to login. I am still unsure as to why $Display_Name and $Email were being returned empty; I do have the "displayName" and "mail" attributes set in Active Directory, but I just wanted to update you about this.

**Comment by ChipwizBen** [comment]
Thanks a lot for looking into this and finding a permanent fix, Phil. In v2.6.0 (in final testing) I've moved nearly all configuration to the DB so that it's changeable from the UI by admins. This is the new line and LDAP_Filter can be configured in the UI (as I know of other companies using uid as a filter):
https://github.com/ChipwizBen/TheMachine/blob/961b07e2de886f68ee044438fec2b9c6f0d37354/HTTP/common.pl#L234

After you update to 2.6.0 you may need to add 'sAMAccountName' to the filter in the UI (the link will be under Home->Management->Configuration). All the other values should be imported into the DB during the install process.

In the past when others have contributed fixes I've acknowledged these contributions in the changelog:
https://github.com/ChipwizBen/TheMachine/blob/961b07e2de886f68ee044438fec2b9c6f0d37354/changelog#L10
https://github.com/ChipwizBen/TheMachine/blob/961b07e2de886f68ee044438fec2b9c6f0d37354/changelog#L25

Please let me know if you'd like to be credited, and if so, how? (e.g. GitHub username, name, or name @ company, etc)

**Comment by philconner** [comment]
No problem Ben, and sure, you can credit me as "Phil Conner"; thanks for this software!
